version: '3'

services:
  app:
    image: node:18
    volumes:
      - ../..:/app
    depends_on:
      - redis
    environment:
      CC_TEST_REPORTER_ID: 4c0674ab7fa1efa186ac5998f89136640d924fabcc0b99ed764bd9fc85043b97
  redis:
    image: redis:5-alpine
